language: php

php:
  - 7.2

git:
  depth: 1

install:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress

script:
  - phpcs -q --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
  - phpunit -c phpunit.xml --testsuite sqlite

after_success:
  - travis_retry php vendor/bin/php-coveralls
