sudo: required

language: php

services:
  - docker
  - mysql

php:
  - 7.4

git:
  depth: 1

before_install:
  - mysql -e 'CREATE DATABASE anonymiser;'
  - printf "\n" | pecl install yaml
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress --ignore-platform-reqs

script:
  - vendor/bib/phpcs -q --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
  - vendor/bin/phpunit -c phpunit.xml --testsuite mysql
