sudo: required

services:
  - docker

git:
  depth: 1

before_install:
  - docker-compose --version

before_script:
  - docker-compose up -d
  - docker-compose ps

script:
  - mkdir ./coverage
  - docker-compose run phpunit -c phpunit.xml
  - docker-compose run phpcs --standard=ruleset.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
