sudo: required

language: php

services:
  - docker
  - mysql

php:
  - 8.0

git:
  depth: 1

before_install:
  - mysql -e 'CREATE DATABASE anonymiser;'
  - printf "\n" | pecl install yaml

install:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress --ignore-platform-reqs

script:
  - vendor/bin/phpcs -q --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
  - vendor/bin/phpunit -c phpunit.xml --testsuite mysql
