sudo: false

language: php

php:
  - 7.1

services:
  - docker

git:
  depth: 1

before_install:
  - mkdir -p ./coverage
  - docker-compose --version
  - docker-compose up --no-start

install:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress

before_script:
  - docker-compose start

script:
  - php vendor/bin/phpcs -q --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
  - sleep 5; docker-compose run php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
