sudo: required

language: php

services:
  - docker
  - mysql

php:
  - 8.0

git:
  depth: 1

before_install:
  - mysql -e 'CREATE DATABASE anonymiser;'
  - printf "\n" | pecl install yaml

install:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress --ignore-platform-reqs

script:
  - vendor/bin/phpcs -q --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
  - DB_DSN='mysql:host=127.0.0.1;dbname=anonymiser;charset=utf8;port=3306' DB_USERNAME='root' vendor/bin/phpunit -c phpunit.xml --testsuite mysql
  - DB_DSN='sqlite::memory:' DB_USERNAME='' vendor/bin/phpunit -c phpunit.xml --testsuite sqlite
