sudo: false

language: php

php:
  - 7.2

services:
  - docker

git:
  depth: 1

before_install:
  - mkdir -p ./coverage
  - pecl install yaml
  - echo "extension = yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress

before_script:
  - docker-compose start

script:
  - php vendor/bin/phpcs -q --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
