sudo: false

language: php

php:
  - 7.2

services:
  - docker

git:
  depth: 1

before_install:
  - docker-compose --version

before_script:
  - mkdir -p ./coverage
  - docker-compose up -d
  - docker-compose ps
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress

script:
  - docker-compose run php vendor/bin/phpunit -c phpunit.xml
  - php vendor/bin/phpcs --standard=ruleset.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
