sudo: false

language: php

dist: trusty

php:
  - 7.1
  - 7.2

before_script:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress

script:
  - vendor/bin/phpunit -c phpunit.xml
  - vendor/bin/phpcs -q -n --colors --standard=ruleset.xml
