sudo: required

language: php

services:
  - docker

php:
  - 7.2

git:
  depth: 1

before_install:
  - mkdir -p ./coverage
  - printf "\n" | pecl install yaml
  - echo "extension = yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress

script:
  - php vendor/bin/phpcs -q --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
  - php vendor/bin/phpunit -c phpunit.xml --testsuite all

after_success:
  - travis_retry php vendor/bin/php-coveralls
