version: "3.3"

services:
  phpunit:
    container_name: phpunnit
    build: ./docker/phpunit
    volumes:
      - ./vendor:/app/vendor:ro
      - ./tests:/app/tests:ro
      - ./src:/app/src:ro
      - ./phpunit.xml:/app/phpunit.xml:ro
      - ./coverage:/app/coverage:rw
      - ./testdox:/app/testdox:rw
    depends_on:
      - mysql

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_anonymiser

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_anonymiser
